# ForTunnels CLI client - formula generated by deploy
class Fortunnels < Formula
  desc "ForTunnels CLI client for secure tunneling"
  homepage "https://fortunnels.ru"
  version "1"

  if OS.mac? && Hardware::CPU.intel?
    url "https://fortunnels.ru/landing-assets/downloads/fortunnels-macos+amd64.tar.gz"
    sha256 "9be00104d9bd0e5a20728431d163bb90d383e248aba78ae009917f732dac7b9c"
  end

  if OS.mac? && Hardware::CPU.arm?
    url "https://fortunnels.ru/landing-assets/downloads/fortunnels-macos+arm64.tar.gz"
    sha256 "d97575eb6eb68247856041b1a2c7bea7ac52a4827ce99e3e94bc5ef9dfcc165d"
  end

  if OS.linux? && Hardware::CPU.intel?
    url "https://fortunnels.ru/landing-assets/downloads/fortunnels-linux+amd64.tar.gz"
    sha256 "678a9329ca6708bee28b564a81483eb959be2542fb27ef06576c4e77ce7a908d"
  end

  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://fortunnels.ru/landing-assets/downloads/fortunnels-linux+arm64.tar.gz"
    sha256 "719c8441f1208106b5ced3d806adc6939f67a66ef2b2ae6f820a71d97f8ec16b"
  end

  def install
    bin.install "fortunnels"
  end

  test do
    system "\#{bin}/fortunnels", "--help"
  end
end

