# ForTunnels CLI client - formula generated by deploy
class Fortunnels < Formula
  desc "ForTunnels CLI client for secure tunneling"
  homepage "https://fortunnels.ru"
  version "4"

  if OS.mac? && Hardware::CPU.intel?
    url "https://fortunnels.ru/landing-assets/downloads/fortunnels-macos+amd64.tar.gz"
    sha256 "0e80776e75e32190cb61d9fd07666512d5703bf46dedad2ba65a1a80862aab20"
  end

  if OS.mac? && Hardware::CPU.arm?
    url "https://fortunnels.ru/landing-assets/downloads/fortunnels-macos+arm64.tar.gz"
    sha256 "4d7a6eaf5a545d6faff89a4c51060d49a94b2449fdb50954286b78686ae038ca"
  end

  if OS.linux? && Hardware::CPU.intel?
    url "https://fortunnels.ru/landing-assets/downloads/fortunnels-linux+amd64.tar.gz"
    sha256 "300c165ecbc745fe3a5810b36855d59a1df34807e4b70a6b0d4c62089a55f6c9"
  end

  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://fortunnels.ru/landing-assets/downloads/fortunnels-linux+arm64.tar.gz"
    sha256 "ede00987821bfdc7af81839302bdc29f2feaba77d59323fbbb46f6fac1b80b1e"
  end

  def install
    bin.install "fortunnels"
  end

  test do
    system "\#{bin}/fortunnels", "--help"
  end
end

